# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Roger Staubli
title: Full Stack Software Engineer
email: roger@staubli-software-solutions.ch
website: https://staubli-software-solutions.ch

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sirroger5000
stackoverflow_username: "15197038"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: rogerstaubli
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: "@rs-crypto-university"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Über Mich
about_profile_image: images/roger.jpg
about_content: | # this will include new lines to allow paragraphs
  Als Softwareentwickler mit 9 Jahren Erfahrung verfüge ich über umfangreiche Kenntnisse in der Entwicklung von Webanwendungen mit <mark>Java</mark>, <mark>Spring Boot</mark> und <mark>Angular</mark>.
  Ich habe an einer Vielzahl von Projekten gearbeitet und dabei wertvolle Erfahrungen in der agilen Entwicklung, der Entwicklung von RESTful APIs und dem Umgang mit verschiedenen Frameworks gesammelt.
  Mein Fachwissen und meine Berufserfahrung decken dabei den gesamten Prozess der Softwareentwicklung ab und reichen von der Anforderungsanalyse über Konzept, Design und Implementation bis zum Testing und dem Betrieb von komplexen Systemen.

  Ich bin stolz auf meine Arbeit an anspruchsvollen Projekten, bei denen ich innovative Lösungen entwickelt habe, um komplexe Probleme zu lösen und die Benutzererfahrung zu verbessern. Ich bin immer bestrebt, meine Fähigkeiten und Kenntnisse zu erweitern und auf dem neuesten Stand der Technologie zu bleiben.

content:
  - title: Berufserfahrung # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Staubli Software Solutions
        link: https://staubli-software-solutions.ch
        # link_text: boringcompany.com
        sub_title: Owner/Freelancer
        caption: August 2020 - heute
        quote: >
          Your Partner for Web Development
        description: | # this will include new lines to allow paragraphs
            - Entwicklung, Support und Hosting von massgeschneiderten Softwarelösungen im Web-Bereich
            - Umsetzung von proprietären Softwarelösungen und Kundenprojekten in unterschiedlichen Geschäftsbereichen wie FinTech, EdTech und DeFi

      - layout: left
        title: c-alm AG
        link: https://c-alm.ch
        # link_text: boringcompany.com
        sub_title: CTO
        caption: Oktober 2018 - August 2020
        quote: >
          The Pension Consultant
        description: | # this will include new lines to allow paragraphs
            - Führen eines 7-köpfigen Softwareentwicklungsteams in der Webentwicklung mit Front- und Backendkomponenten
            - Aufbau und Unterhalt der firmenspezifischen Continuous Integration und Continuous Delivery (CI/CD) bestehend aus Versionskontrolle, Testautomaten und der Übersetzung des Codes innerhalb von automatisierten Pipelines
            - Erarbeiten von kundenspezifischen Offerten für Digitalisierungsprojekte in der 2. Säule mit anschliessender Präsentation der technischen Lösung vor der Geschäftsführung des Kunden

      - layout: left
        title: c-alm AG
        link: https://c-alm.ch
        # link_text: boringcompany.com
        sub_title: Full Stack Software Engineer
        caption: November 2015 - September 2018
        quote: >
          The Pension Consultant
        description: | # this will include new lines to allow paragraphs
            - Durchführung von kompletten Software-Lebenszyklen in verschiedenen Kundenprojekten, wie Webseiten oder Webportalen mit agilen Methoden
            - Entwicklung eines Webportals in Kooperation mit einem Anbieter für Verwaltungssysteme in der 2. Säule

  - title: Ausbildung # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universität Zürich
        caption: 2019 - 2021
        sub_title: MSc in Informatik

        description: | # this will include new lines to allow paragraphs
          - Hauptfach: Wirtschaftsinformatik
          - Nebenfach: Volkswirtschaftslehre
          - Durchschnitt: 5.5 (summa cum laude)

      - layout: left
        title: Universität Zürich
        caption: 2013 - 2016
        sub_title: BA in Volkswirtschaftslehre

        description: | # this will include new lines to allow paragraphs
          - Hauptfach: Volkswirtschaftslehre
          - Durchschnitt: 5.5 (summa cum laude)


  - title: Projekte # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Grizzly.fi, MonetaDAO
        link: grizzly.fi
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Defi for everyone!
        description: | # this will include new lines to allow paragraphs
          Grizzly.fi ist eine Krypto-Plattform, die das Investieren in die besten Möglichkeiten des DeFi Bereichs vereinfacht. Grizzly.fi ist ein Hub für langfristigen Kapitalaufbau. Das Projekt aggregiert verschiedene DeFi Protokolle und Ertragsquellen mit Fokus auf Stabilität und Sicherheit.

          Das Moneta DAO ist eine On-Chain-Community, die die Entwicklung des Moneta-Ökosystems steuert, einem auf Stablecoins ausgerichteten Ökosystem, einschließlich des DeFi-Franc. Moneta DAO wurde von Grizzly.fi entwickelt.

          <strong>Position</strong>

          Smart Contract Engineer, Software-Entwickler Backend

          <strong>Technologien</strong>

          <mark>Solidity</mark>, <mark>NodeJS</mark>, <mark>Hardhat</mark>, <mark>ethers.js</mark>, <mark>Angular</mark>, <mark>JWT</mark>, <mark>Docker</mark>

      - layout: top-middle
        title: Smart Dossier
        # link: grizzly.fi
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The most dynamic patient dossier available
        description: | # this will include new lines to allow paragraphs
          Smart Dossier ist eine Webplattform, die es TCM-Mediziner erlaubt, ihre Patientendossiers zu digitalisieren. Die Patientendossiers werden aus einer frei wählbaren Konfiguration erstellt, was es den Ärzten erlaubt, diese auf ihre Bedürfnisse anzupassen. Die Plattform ist mit OneDoc verbunden, wodurch der Kalender und die Patienten synchronisiert werden können.

          <strong>Position</strong>

          Backend Software-Engineer

          <strong>Technologien</strong>

          <mark>Java</mark>, <mark>Spring Boot</mark>, <mark>MongoDB</mark>, <mark>Docker</mark>, <mark>JWT</mark>

      - layout: top-middle
        title: edumint
        link: edumint.io
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Simple, Secure and Verifiable Digital Certificates
        description: | # this will include new lines to allow paragraphs
          Edumint.io ist eine Web-Plattform, die sich auf die Spezialisierung von Zertifikaten in Form von NFTs konzentriert. Die Plattform erlaubt es Bildungsinstituten sich zu registrieren, Templates von Zertifikaten zu erstellen und dann direkt als NFT auf die Blockchain zu schreiben. Dadurch wird ein persönlicher QR-Code erstellt, welcher zusätzlich zum physischen Zertifikat ausgegeben werden kann. Firmen oder andere Stakeholder können anschliessend das Zertifikat verifizieren und sicherstellen, von welchem Bildungsinstitut es ausgegeben worden ist und dass es von niemand verändert oder verfälscht worden ist.

          <strong>Position</strong>

          Software-Entwickler Frontend, Backend und Smart Contract

          <strong>Technologien</strong>

          <mark>Solidity</mark>, <mark>NodeJS</mark>, <mark>Hardhat</mark>, <mark>ethers.js</mark>, <mark>Angular</mark>, <mark>JWT</mark>, <mark>IPFS</mark>, <mark>Docker</mark>

      - layout: top-middle
        title: BHFS Riskprofiler
        link: https://bhfs.ch/index.php/demo-tool/
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Riskprofiling based on Science
        description: | # this will include new lines to allow paragraphs
          Implementierung eines Riskprofiler Tools für den Kunden. Das Tool besteht aus drei Teilen: Risiko Diagnostics, Training und Risikoprofilierung. Im Tool werden die neusten wissenschaftlichen Erkenntnisse abgebildet und zeigen dem User in einem interaktiven GUI, seine Risikofähigkeit und Risikoneigung auf.

          <strong>Position</strong>

          Frontend Software Engineer

          <strong>Technologien</strong>

          <mark>Angular</mark>, <mark>NodeJS</mark>, <mark>SVG</mark>, <mark>Docker</mark>, <mark>Azure</mark>

      - layout: top-middle
        title: Plattform Freiwilligenarbeit
        link: https://freiwilligenarbeit-sursee.ch
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The Platform for Voluntray Work
        description: | # this will include new lines to allow paragraphs
          Erstellung der Plattform Freiwilligenarbeit für die Stadt Sempach und Sursee, wo Organisationen sich registrieren können und Angebote und Inserate aufschalten können

          <strong>Position</strong>

          Frontend/Backend Software-Engineer

          <strong>Technologien</strong>

          <mark>Angular</mark>, <mark>Java</mark>, <mark>Spring Boot</mark>, <mark>JPA</mark>, <mark>Postgresql</mark>, <mark>Docker</mark>


      - layout: top-middle
        title: Math-learn
        link: https://math-learn.ch
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An LMS for Everyday Schooling
        description: | # this will include new lines to allow paragraphs
          Math-learn ist ein Learning Management System (LMS) für Lehrpersonen, um ihre Kurse und Schüler zu verwalten. Dabei können Theorieelemente, Aufgaben und Abgaben erstellt werden und von der Lehrperson in einem intuitiven GUI verwaltet werden.

          <strong>Position</strong>

          Frontend/Backend Software-Engineer

          <strong>Technologien</strong>

          <mark>Java</mark>, <mark>Angular</mark>, <mark>Spring Boot</mark>, <mark>MariaDB</mark>, <mark>JPA</mark>, <mark>Docker</mark>


      - layout: top-middle
        title: Stiftung Auffangeinrichtung
        link: https://aeis.ch
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Homemade CMS
        description: | # this will include new lines to allow paragraphs
          Neuentwicklung des Webauftritts der Stiftung Auffangeinrichtung BVG. Dazu zählten ein eigens entwickeltes CMS, Erklärvideos und eine Suche basierend auf machine learning

          <strong>Position</strong>

          Software Architekt/Technical Lead

          <strong>Technologien</strong>

          <mark>Angular</mark>, <mark>Java</mark>, <mark>Spring Boot</mark>, <mark>MariaDB</mark>, <mark>Docker</mark>, <mark>Jenkins</mark>


      - layout: top-middle
        title: Rentenrechner BVG
        # link: grizzly.fi
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The Configurable Pension Calculator
        description: | # this will include new lines to allow paragraphs
          Erstellung von unterschiedlichen, webbasierten BVG-Rentenrechner für Pensionskassen. Dabei können Leistungen angesehen werden und Szenarien wie Frühpensionierung, Einkauf etc. durchgeführt werden.

          <strong>Position</strong>

          Software Architekt/Full Stack Software Engineer

          <strong>Technologien</strong>

          <mark>Java</mark>, <mark>Spring Boot</mark>, <mark>Angular</mark>, <mark>MariaDB</mark>, <mark>Docker</mark>, <mark>Jenkins</mark>

      - layout: top-middle
        title: Real-DB
        link: https://real-db.swiss
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Making Illiquid Assets Accessible
        description: | # this will include new lines to allow paragraphs
          Eigenentwicklung der RealDB, eine Web-Plattform, die es Providern ermöglicht, illiquide Investments zu listen. Investoren können diese einzigartigen Investments dort finden und Kennzahlen, Reports etc. anschauen für die Due Diligence.

          <strong>Position</strong>

          Software Architekt/Full Stack Software Engineer

          <strong>Technologien</strong>

          <mark>Java</mark>, <mark>Spring Boot</mark>, <mark>Angular</mark>, <mark>MariaDB</mark>, <mark>Docker</mark>, <mark>Jenkins</mark>

  - title: Noch ein wenig mehr über mich...
    layout: text
    content: | # this will include new lines to allow paragraphs
      Neben meinem Interesse an der Software-Entwicklung sind einige meiner anderen Interessen und Hobbys:
      - Gitarre spielen
      - Zaubern
      - Kochen

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
